name: Publish package to the Sonatype Repository
on: [pull_requests]
#  release:
#    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3

      # This shouldn't be needed since we hooked this up to all requests, but since we're publishing let's make sure
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # burrunan/gradle-cache-action@v1
      - name: Run check and sign artifacts
        uses: gradle/gradle-build-action
        with:
          arguments: build check
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

#      - name: Publish package
#        uses: burrunan/gradle-cache-action@v1
#        with:
#          arguments: publishMavenPublicationToOssrhRepository
#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}